services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cabag\BackendProgress\:
    resource: '../Classes/*'

  Cabag\BackendProgress\Examples\Command\ExampleProgressBarCommand:
    tags:
      - name: 'console.command'
        command: 'backend-progress:test'
